---
- name: restart workers
  docker_service:
    project_src: /srv/buildbot
    files:
      - docker-compose.yml
      - docker-compose.worker-prod.yml
    services:
      "{{ workers }}"
    state: present
    restarted: true
