all:
  children:
    vm1:
      hosts:
        192.168.10.2:
      vars:
        ansible_python_interpreter: /usr/bin/python3
        buildbot_master_host: 192.168.10.3
        workers:
          - amigaos
    vm2:
      hosts:
        192.168.10.3:
      vars:
        internal_buildbot_port: 8010
        ssl_domains:
          - buildbot.scummvm.org
        ssl_selfsigned: yes
        workers:
          - debian-x86_64
  vars:
    users:
      - name: user
        groups: sudo
