---
- name: Check if Buildbot configuration already exists
  command: test -f /srv/buildbot/docker-compose.yml
  register: buildbot_exists
  failed_when: false
  tags:
    - buildbot_worker
    - services

- name: Get list of available services
  command: docker-compose config --services
  args:
    chdir: /srv/buildbot
  register: docker_services
  when: buildbot_exists.rc == 0
  tags:
    - buildbot_worker
    - services

# TODO: Using `state: present stopped: true` causes all the images things to be
# downloaded; using `state: absent` does not work with `services`
# - name: Stop old Buildbot workers
#   docker_service:
#     project_src: /srv/buildbot
#     files:
#       - docker-compose.yml
#     services:
#       "{{ docker_services.stdout_lines | difference(['web', 'buildbot']) | difference(workers) }}"
#     state: absent
#   when: buildbot_exists.rc == 0
#   tags:
#     - buildbot_worker
#     - services
- name: Stop old Buildbot workers
  command: >
    docker-compose stop {{ docker_services.stdout_lines |
                           difference(['web', 'buildbot']) |
                           difference(workers) |
                           join(' ') }}
  args:
    chdir: /srv/buildbot
  when: buildbot_exists.rc == 0
  tags:
    - buildbot_worker
    - services

- name: Retrieve Buildbot configuration
  git:
    repo: https://github.com/csnover/scummvm-buildbot.git
    dest: /srv/buildbot
    force: yes
  notify:
    - restart workers
  tags:
    - buildbot_worker
    - configuration

- name: Install Buildbot worker settings
  template:
    src: docker-compose.worker-prod.yml.j2
    dest: /srv/buildbot/docker-compose.worker-prod.yml
  notify:
    - restart workers
  tags:
    - buildbot_worker
    - configuration

- name: Run Buildbot workers
  docker_service:
    project_src: /srv/buildbot
    files:
      - docker-compose.yml
      - docker-compose.worker-prod.yml
    services:
      "{{ workers }}"
    state: present
  tags:
    - buildbot_worker
    - services
